Im gui
knot-alot/knoting pull request #21
Opened 2022-02-24 14:55 UTC by BeardyKing

2022-03-01 15:59 UTC, lmariscal commented on .gitmodules
> +	branch = docking
https://git-scm.com/docs/gitmodules

Didn't know this was possible :ok_hand: .

2022-03-01 17:05 UTC, lmariscal requested changes
Minor details, overall great.

2022-03-01 17:16 UTC, BertTDev reviewed
Very nice, look forward to putting this altogether in the editor

2022-03-01 17:16 UTC, BertTDev commented on core/src/engine.cpp
> +    bgfx::frame();
Should this be handled inside one of the renderers?

2022-03-01 19:35 UTC, BeardyKing commented on core/src/engine.cpp
> +    bgfx::frame();
I agree this bgfx function should be moved to some internal engine function such as 'swap_frame()' as that's what it's doing

2022-03-01 19:38 UTC, BeardyKing commented on core/src/transform.cpp
> +glm::mat4 Transform::get_model_matrix() const {
oops this was added for the screenshot for the technical document and wasn't meant to be updated for the actual project

2022-03-01 19:39 UTC, BeardyKing commented on core/src/window.cpp
> +    int glfw_init_res = glfwInit(), debug_editor_resize_flag(true);
this is meant to be inside of the initialization of the class and has been changed

2022-03-01 19:41 UTC, BeardyKing commented on core/inc/knoting/window.h
> +    void set_window_height(int height) { m_height = height; };
will remove set_window_width/height and replace with a 'set_window_size(vec2i size); function that calls 'recreate_framebuffer' with the new member variables that are set

2022-03-03 19:32 UTC, BertTDev reviewed
LGTM!

2022-03-03 23:39 UTC, lmariscal approved these changes
LGTM

2022-03-03 23:39 UTC, merged